{$Template->assignByRef('contact', $entity)}
{assign var='name' value=$contact->getName()}
{if $contact->isCompany()}{$Template->assign('inputCiClass', 'contactLabel')}{$name->renderAttribute('companyName', 'input')}{$Template->assign('inputCiClass', 0)}<br />{/if}
{if !$contact->isCompany()}{$Template->assign('inputCiClass', 'contactLabel')}{/if}{if $user->displayContactField('prefix')}{$name->renderAttribute('prefix', 'input')}{/if}{if $user->getAttribute('myContactsPreferences_nameFormat') eq 'last_first'}{$name->renderAttribute('last', 'input')}, {$name->renderAttribute('first', 'input')}{if $user->displayContactField('middle')}{$name->renderAttribute('middle', 'input')}{/if}{else}{$name->renderAttribute('first', 'input')}{if $user->displayContactField('middle')}{$name->renderAttribute('middle', 'input')}{/if}{$name->renderAttribute('last', 'input')}{/if}{if $user->displayContactField('suffix')}{$name->renderAttribute('suffix', 'input')}{/if}{if !$contact->isCompany()}{$Template->assign('inputCiClass', 0)}{/if}{if $user->displayContactField('maiden')}({$name->renderAttribute('maiden', 'input')}){/if}<br />
{if $user->displayContactField('phonetic')}{if $user->getAttribute('myContactsPreferences_nameFormat') eq 'last_first'}{$name->renderAttribute('phoneticLast', 'input')}, {$name->renderAttribute('phoneticFirst', 'input')}{if $user->displayContactField('middle')}{$name->renderAttribute('phoneticMiddle', 'input')}{/if}{else}{$name->renderAttribute('phoneticFirst', 'input')}{if $user->displayContactField('middle')}{$name->renderAttribute('phoneticMiddle', 'input')}{/if}{$name->renderAttribute('phoneticLast', 'input')}{/if}<br />{/if}
{if $user->displayContactField('nickname')}"{if !$contact->isCompany()}{$Template->assign('inputCiStyle', 'font-weight: bold;')}{/if}{$name->renderAttribute('nickname', 'input')}{if !$contact->isCompany()}{$Template->assign('inputCiStyle', 0)}{/if}"<br />{/if}
{if $user->displayContactField('gender')}{$contact->renderAttribute('gender', 'input')}<br />{/if}
{if $user->displayContactField('jobTitle') || $user->displayContactField('department')}{if $user->displayContactField('jobTitle')}{$name->renderAttribute('jobTitle', 'input')}{/if}{if $user->displayContactField('jobTitle') && $user->displayContactField('department')} - {/if}{if $user->displayContactField('department')}{$name->renderAttribute('department', 'input')}{/if}<br />{/if}
{if !$contact->isCompany()}{$name->renderAttribute('companyName', 'input')}<br />{/if}
{$name->renderAttribute('company', 'input')}
